services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: ${grafana_admin_username}
      GF_SECURITY_ADMIN_PASSWORD: ${grafana_admin_password}
      GF_USERS_ALLOW_SIGN_UP: "false"
      INFLUXDB_TOKEN: ${influxdb2_admin_token}
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana
      - ./Grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./Grafana/dashboards:/etc/grafana/provisioning/dashboards/
    depends_on:
      - influxdb2

  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    restart: unless-stopped
    ports:
      - '8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${influxdb2_admin_username}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${influxdb2_admin_password}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${influxdb2_admin_token}
      DOCKER_INFLUXDB_INIT_ORG: WeatherOrg
      DOCKER_INFLUXDB_INIT_BUCKET: WeatherBucket
    networks:
      - monitoring
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2

networks:
  monitoring:

volumes:
  grafana-data:
  influxdb2-data:
  influxdb2-config:
